.TH LIBSIMPLE_ENSTRNDUP 3 2018-10-27 libsimple
.SH NAME
libsimple_enstrndup \- duplicate the beginning of a string
.SH SYNOPSIS
.nf
#include <libsimple.h>

char *libsimple_strndupa(const char *\fIs\fP, size_t \fIn\fP);
char *libsimple_enstrndup(int \fIstatus\fP, const char *\fIs\fP, size_t \fIn\fP);
static inline char *libsimple_estrndup(const char *\fIs\fP, size_t \fIn\fP);

#ifndef strndupa
# define strndupa libsimple_strndupa
#endif
#ifndef enstrndup
# define enstrndup libsimple_enstrndup
#endif
#ifndef estrndup
# define estrndup libsimple_estrndup
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_enstrndup ()
and
.BR libsimple_estrndup ()
functions are versions of the
.BR strndup (3)
function that call the
.BR libsimple_enprintf (3)
function on failure, causing the process to print
an error message and exit. See
.BR libsimple_enprintf (3)
for more information.
.PP
The
.BR libsimple_strndupa ()
function is implemented as a macro and is a version
of the
.BR strndup (3)
function that uses allocates the memory on the stack
rather than on the heap, causing the return pointer
to become invalid when the calling function returns.
.SH RETURN VALUE
Upon successful completion, the
.BR libsimple_strndupa (),
.BR libsimple_enstrndup (),
and
.BR libsimple_estrndup ()
functions return a non-null pointer, on failure the
.BR libsimple_enstrndup (),
and
.BR libsimple_estrndup ()
functions exit the process group. The
.BR libsimple_strndupa ()
function cannot fail, however the kernel
can kill the process with a
.B SIGSEGV
signal if the memory cannot be allocated.
.PP
The returned pointer should be deallocated when it
is no longer needed, except for the pointer returned
by the
.BR libsimple_strndupa ()
function, it is automatically deallocated when the
calling function returns.
.SH ERRORS
None.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strndupa (),
.br
.BR libsimple_enstrndup (),
.br
.BR libsimple_estrndup (),
T}	Thread safety	MT-Safe
T{
.BR libsimple_strndupa (),
.br
.BR libsimple_enstrndup (),
.br
.BR libsimple_estrndup (),
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strndupa (),
.br
.BR libsimple_enstrndup (),
.br
.BR libsimple_estrndup (),
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_enstrdup (3),
.BR libsimple_memdup (3),
.BR libsimple_aligned_memdup (3),
.BR strndup (3),
.BR strdup (3)
