.TH LIBSIMPLE_RAWMEMCASECHR 3 2018-10-21 libsimple
.SH NAME
libsimple_rawmemcasechr \- find byte in memory
.SH SYNOPSIS
.nf
#include <libsimple.h>

void *libsimple_rawmemcasechr(const void *\fIs\fP, int \fIc\fP);

#ifndef rawmemcasechr
# define rawmemcasechr libsimple_rawmemcasechr
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_rawmemcasechr ()
function scans the memory segment
.I s
for the first occurence of the byte
.I c
(it is converted to a
.BR char ).
.PP
The
.BR libsimple_rawmemcasechr ()
function assumes there is at least one
occurence, its behaviour is undefined
if this is not the case.
.PP
The comparison is case-insensitive.
.SH RETURN VALUE
The
.BR libsimple_rawmemcasechr ()
function returns the pointer
.I s
with a minimal offset such that
.IR tolower(*r)==tolower(c) ,
where
.I r
is the returned pointer.
.SH ERRORS
The
.BR libsimple_rawmemcasechr ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_rawmemcasechr ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_rawmemcasechr ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_rawmemcasechr ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_rawmemchr (3),
.BR libsimple_rawmemrcasechr (3),
.BR libsimple_memcasechr (3)
