.TH LIBSIMPLE_STRNENDS 3 2018-10-23 libsimple
.SH NAME
libsimple_strnends \- check the beginning of a string
.SH SYNOPSIS
.nf
#include <libsimple.h>

int libsimple_strnends(const char *\fIs\fP, const char *\fIt\fP, size_t \fIn\fP);

#ifndef strnends
# define strnends libsimple_strnends
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_strnends ()
function checks whether the string
.IR s ,
truncated to
.I n
bytes unless it is shorter,
ends with the string
.IR t .
.PP
The comparison is case-sensitive.
.SH RETURN VALUE
The
.BR libsimple_strnends ()
function returns 1 if the string
.I s
ends with the string
.IR t ,
otherwise it returns 0.
.SH ERRORS
The
.BR libsimple_strnends ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strnends ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strnends ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strnends ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_strncaseends (3),
.BR libsimple_strnstarts (3),
.BR libsimple_strrnstr (3),
.BR libsimple_strends (3),
.BR libsimple_memends (3)
