.TH LIBSIMPLE_MEMCASECMP 3 2018-10-21 libsimple
.SH NAME
libsimple_memcasecmp \- compare two memory segments
.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline int libsimple_memcasecmp(const void *\fIa\fP, const void *\fIb\fP, size_t \fIn\fP);

#ifndef memcasecmp
# define memcasecmp libsimple_memcasecmp
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_memcasecmp ()
function compares the first
.I n
bytes of
.I a
and
.IR b .
.PP
The comparison is case-insensitive and made as
if the strings were converted to lowercase and as
.IR "unsigned char *" s.
.SH RETURN VALUE
The
.BR libsimple_memcasecmp ()
function returns a negative value if
.I a
is less than
.IR b ,
a positive value if
.I a
is greater than
.IR b ,
and 0 otherwise.
.SH ERRORS
The
.BR libsimple_memcasecmp ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_memcasecmp ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_memcasecmp ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_memcasecmp ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_memcaseeq (3),
.BR libsimple_memcaseeqlen (3),
.BR memcmp (3)
