.TH LIBSIMPLE_STRCASEEQNUL 3 2018-10-23 libsimple
.SH NAME
libsimple_strcaseeqnul \- compare two strings
.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline int libsimple_strcaseeqnul(const char *\fIa\fP, const char *\fIb\fP);

#ifndef strcaseeqnul
# define strcaseeqnul libsimple_strcaseeqnul
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_strcaseeqnul ()
function compares the strings
.I a
and
.IR b ,
both of which may be
.BR NULL .
.PP
The comparison is case-insensitive.
.IR "unsigned char *" s.
.SH RETURN VALUE
The
.BR libsimple_strcaseeqnul ()
function returns 1 if the strings are equals,
with the possible exception of the case,
otherwise it returns 0.
.SH ERRORS
The
.BR libsimple_strcaseeqnul ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strcaseeqnul ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strcaseeqnul ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strcaseeqnul ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_strcaseeq (3),
.BR libsimple_streqnul (3),
.BR libsimple_strcasecmpnul (3),
.BR libsimple_strncaseeqnul (3),
.BR libsimple_memcaseeq (3),
.BR strcasecmp (3)
