.TH LIBSIMPLE_STRRCASESTR 3 2018-10-21 libsimple
.SH NAME
libsimple_strrcasestr \- find a substring in a string
.SH SYNOPSIS
.nf
#include <libsimple.h>

char *libsimple_strrcasestr(const char *\fIhaystack\fP, const char *\fIneedle\fP);

#ifndef strrcasestr
# define strrcasestr libsimple_strrcasestr
#endif
.fi

Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_strrcasestr ()
function scans the string
.I haystack
the last occurrence of the substring
.IR needle .
.PP
The comparison is case-insensitive.
.SH RETURN VALUE
The
.BR libsimple_strrcasestr ()
function returns the pointer
.I haystack
with a maximal offset such that
.I !*r
begins with
.IR needle ,
where
.I r
is the returned pointer.
.SH ERRORS
The
.BR libsimple_strrcasestr ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strrcasestr ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strrcasestr ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strrcasestr ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_strrstr (3),
.BR libsimple_strcasestr (3)
