.TH LIBSIMPLE_STRNEQNUL 3 2018-10-23 libsimple
.SH NAME
libsimple_strneqnul \- compare two strings
.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline int libsimple_strneqnul(const char *\fIa\fP, const char *\fIb\fP, size_t \fIn\fP);

#ifndef strneqnul
# define strneqnul libsimple_strneqnul
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_strneqnul ()
function compares the strings
.IR a ,
truncated to
.I n
bytes unless it is shorter,
and
.IR b ,
truncated to
.I n
bytes unless it is shorter,
both of which may be
.BR NULL .
.PP
The comparison is case-sensitive.
.SH RETURN VALUE
The
.BR libsimple_strneqnul ()
function returns 1 if the strings are equals,
otherwise it returns 0.
.SH ERRORS
The
.BR libsimple_strneqnul ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strneqnul ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strneqnul ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strneqnul ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_strneq (3),
.BR libsimple_strncaseeqnul (3),
.BR libsimple_strncmpnul (3),
.BR libsimple_streqnul (3),
.BR libsimple_memeq (3),
.BR strncmp (3)
