.TH LIBSIMPLE_MEMCASEENDS 3 2018-10-21 libsimple
.SH NAME
libsimple_memcaseends \- checks end of memory
.SH SYNOPSIS
.nf
#include <libsimple.h>

void *libsimple_memcaseends(const void *\fIs\fP, size_t \fIn\fP, const void *\fIt\fP, size_t \fIm\fP);

#ifndef memcaseends
# define memcaseends libsimple_memcaseends
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_memcaseends ()
function checks whether the
.I n
is at least as great as
.I m
and that the
.I m
last bytes of
.IR s ,
with the size
.IR n ,
is the same as the
.I m
first bytes of
.IR t .
.PP
The comparison is case-insensitive.
.SH RETURN VALUE
The
.BR libsimple_memcaseends ()
function returns 1 if
.I s
ends with
.IR t ,
otherwise it returns 0.
.SH ERRORS
The
.BR libsimple_memcaseends ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_memcaseends ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_memcaseends ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_memcaseends ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_memends (3),
.BR libsimple_memcasestarts (3),
.BR libsimple_memrcasemem (3)
