/* See LICENSE file for copyright and license details. */

/* TODO man, doc, test */


#define LIBSIMPLE_CHAR_NUL '\x00'
#ifndef CHAR_NUL
# define CHAR_NUL LIBSIMPLE_CHAR_NUL
#endif
#define LIBSIMPLE_CHAR_NULL LIBSIMPLE_CHAR_NUL
#ifndef CHAR_NULL
# define CHAR_NULL LIBSIMPLE_CHAR_NULL
#endif

#define LIBSIMPLE_CHAR_SOH '\x01'
#ifndef CHAR_SOH
# define CHAR_SOH LIBSIMPLE_CHAR_SOH
#endif
#define LIBSIMPLE_CHAR_START_OF_HEADING LIBSIMPLE_CHAR_SOH
#ifndef CHAR_START_OF_HEADING
# define CHAR_START_OF_HEADING LIBSIMPLE_CHAR_START_OF_HEADING
#endif

#define LIBSIMPLE_CHAR_STX '\x02'
#ifndef CHAR_STX
# define CHAR_STX LIBSIMPLE_CHAR_STX
#endif
#define LIBSIMPLE_CHAR_START_OF_TEXT LIBSIMPLE_CHAR_STX
#ifndef CHAR_START_OF_TEXT
# define CHAR_START_OF_TEXT LIBSIMPLE_CHAR_START_OF_TEXT
#endif

#define LIBSIMPLE_CHAR_ETX '\x03'
#ifndef CHAR_ETX
# define CHAR_ETX LIBSIMPLE_CHAR_ETX
#endif
#define LIBSIMPLE_CHAR_END_OF_TEXT LIBSIMPLE_CHAR_ETX
#ifndef CHAR_END_OF_TEXT
# define CHAR_END_OF_TEXT LIBSIMPLE_CHAR_END_OF_TEXT
#endif

#define LIBSIMPLE_CHAR_EOT '\x04'
#ifndef CHAR_EOT
# define CHAR_EOT LIBSIMPLE_CHAR_EOT
#endif
#define LIBSIMPLE_CHAR_END_OF_TRANSMISSION LIBSIMPLE_CHAR_EOT
#ifndef CHAR_END_OF_TRANSMISSION
# define CHAR_END_OF_TRANSMISSION LIBSIMPLE_CHAR_END_OF_TRANSMISSION
#endif

#define LIBSIMPLE_CHAR_ENQ '\x05'
#ifndef CHAR_ENQ
# define CHAR_ENQ LIBSIMPLE_CHAR_ENQ
#endif
#define LIBSIMPLE_CHAR_ENQUIRY LIBSIMPLE_CHAR_ENQ
#ifndef CHAR_ENQUIRY
# define CHAR_ENQUIRY LIBSIMPLE_CHAR_ENQUIRY
#endif

#define LIBSIMPLE_CHAR_ACK '\x06'
#ifndef CHAR_ACK
# define CHAR_ACK LIBSIMPLE_CHAR_ACK
#endif
#define LIBSIMPLE_CHAR_ACKNOWLEDGE LIBSIMPLE_CHAR_ACK
#ifndef CHAR_ACKNOWLEDGE
# define CHAR_ACKNOWLEDGE LIBSIMPLE_CHAR_ACKNOWLEDGE
#endif

#define LIBSIMPLE_CHAR_BEL '\x07'
#ifndef CHAR_BEL
# define CHAR_BEL LIBSIMPLE_CHAR_BEL
#endif
#define LIBSIMPLE_CHAR_BELL LIBSIMPLE_CHAR_BEL
#ifndef CHAR_BELL
# define CHAR_BELL LIBSIMPLE_CHAR_BELL
#endif

#define LIBSIMPLE_CHAR_BS '\x08'
#ifndef CHAR_BS
# define CHAR_BS LIBSIMPLE_CHAR_BS
#endif
#define LIBSIMPLE_CHAR_BACKSPACE LIBSIMPLE_CHAR_BS
#ifndef CHAR_BACKSPACE
# define CHAR_BACKSPACE LIBSIMPLE_CHAR_BACKSPACE
#endif

#define LIBSIMPLE_CHAR_HT '\x09'
#ifndef CHAR_HT
# define CHAR_HT LIBSIMPLE_CHAR_HT
#endif
#define LIBSIMPLE_CHAR_HORIZONTAL_TABULATION LIBSIMPLE_CHAR_HT
#ifndef CHAR_HORIZONTAL_TABULATION
# define CHAR_HORIZONTAL_TABULATION LIBSIMPLE_CHAR_HORIZONTAL_TABULATION
#endif

#define LIBSIMPLE_CHAR_LF '\x0A'
#ifndef CHAR_LF
# define CHAR_LF LIBSIMPLE_CHAR_LF
#endif
#define LIBSIMPLE_CHAR_LINE_FEED LIBSIMPLE_CHAR_LF
#ifndef CHAR_LINE_FEED
# define CHAR_LINE_FEED LIBSIMPLE_CHAR_LINE_FEED
#endif

#define LIBSIMPLE_CHAR_VT '\x0B'
#ifndef CHAR_VT
# define CHAR_VT LIBSIMPLE_CHAR_VT
#endif
#define LIBSIMPLE_CHAR_VERTICAL_TABULATION LIBSIMPLE_CHAR_VT
#ifndef CHAR_VERTICAL_TABULATION
# define CHAR_VERTICAL_TABULATION LIBSIMPLE_CHAR_VERTICAL_TABULATION
#endif

#define LIBSIMPLE_CHAR_FF '\x0C'
#ifndef CHAR_FF
# define CHAR_FF LIBSIMPLE_CHAR_FF
#endif
#define LIBSIMPLE_CHAR_FORM_FEED LIBSIMPLE_CHAR_FF
#ifndef CHAR_FORM_FEED
# define CHAR_FORM_FEED LIBSIMPLE_CHAR_FORM_FEED
#endif

#define LIBSIMPLE_CHAR_CR '\x0D'
#ifndef CHAR_CR
# define CHAR_CR LIBSIMPLE_CHAR_CR
#endif
#define LIBSIMPLE_CHAR_CARRIAGE_RETURN LIBSIMPLE_CHAR_CR
#ifndef CHAR_CARRIAGE_RETURN
# define CHAR_CARRIAGE_RETURN LIBSIMPLE_CHAR_CARRIAGE_RETURN
#endif

#define LIBSIMPLE_CHAR_SO '\x0E'
#ifndef CHAR_SO
# define CHAR_SO LIBSIMPLE_CHAR_SO
#endif
#define LIBSIMPLE_CHAR_SHIFT_OUT LIBSIMPLE_CHAR_SO
#ifndef CHAR_SHIFT_OUT
# define CHAR_SHIFT_OUT LIBSIMPLE_CHAR_SHIFT_OUT
#endif

#define LIBSIMPLE_CHAR_SI '\x0F'
#ifndef CHAR_SI
# define CHAR_SI LIBSIMPLE_CHAR_SI
#endif
#define LIBSIMPLE_CHAR_SHIFT_IN LIBSIMPLE_CHAR_SI
#ifndef CHAR_SHIFT_IN
# define CHAR_SHIFT_IN LIBSIMPLE_CHAR_SHIFT_IN
#endif

#define LIBSIMPLE_CHAR_DLE '\x10'
#ifndef CHAR_DLE
# define CHAR_DLE LIBSIMPLE_CHAR_DLE
#endif
#define LIBSIMPLE_CHAR_DATA_LINK_ESCAPE LIBSIMPLE_CHAR_DLE
#ifndef CHAR_DATA_LINK_ESCAPE
# define CHAR_DATA_LINK_ESCAPE LIBSIMPLE_CHAR_DATA_LINK_ESCAPE
#endif

#define LIBSIMPLE_CHAR_DC1 '\x11'
#ifndef CHAR_DC1
# define CHAR_DC1 LIBSIMPLE_CHAR_DC1
#endif
#define LIBSIMPLE_CHAR_DEVICE_CONTROL_1 LIBSIMPLE_CHAR_DC1
#ifndef CHAR_DEVICE_CONTROL_1
# define CHAR_DEVICE_CONTROL_1 LIBSIMPLE_CHAR_DEVICE_CONTROL_1
#endif

#define LIBSIMPLE_CHAR_DC2 '\x12'
#ifndef CHAR_DC2
# define CHAR_DC2 LIBSIMPLE_CHAR_DC2
#endif
#define LIBSIMPLE_CHAR_DEVICE_CONTROL_2 LIBSIMPLE_CHAR_DC2
#ifndef CHAR_DEVICE_CONTROL_2
# define CHAR_DEVICE_CONTROL_2 LIBSIMPLE_CHAR_DEVICE_CONTROL_2
#endif

#define LIBSIMPLE_CHAR_DC3 '\x13'
#ifndef CHAR_DC3
# define CHAR_DC3 LIBSIMPLE_CHAR_DC3
#endif
#define LIBSIMPLE_CHAR_DEVICE_CONTROL_3 LIBSIMPLE_CHAR_DC3
#ifndef CHAR_DEVICE_CONTROL_3
# define CHAR_DEVICE_CONTROL_3 LIBSIMPLE_CHAR_DEVICE_CONTROL_3
#endif

#define LIBSIMPLE_CHAR_DC4 '\x14'
#ifndef CHAR_DC4
# define CHAR_DC4 LIBSIMPLE_CHAR_DC4
#endif
#define LIBSIMPLE_CHAR_DEVICE_CONTROL_4 LIBSIMPLE_CHAR_DC4
#ifndef CHAR_DEVICE_CONTROL_4
# define CHAR_DEVICE_CONTROL_4 LIBSIMPLE_CHAR_DEVICE_CONTROL_4
#endif

#define LIBSIMPLE_CHAR_NAK '\x15'
#ifndef CHAR_NAK
# define CHAR_NAK LIBSIMPLE_CHAR_NAK
#endif
#define LIBSIMPLE_CHAR_NEGATIVE_ACKNOWLEDGE LIBSIMPLE_CHAR_NAK
#ifndef CHAR_NEGATIVE_ACKNOWLEDGE
# define CHAR_NEGATIVE_ACKNOWLEDGE LIBSIMPLE_CHAR_NEGATIVE_ACKNOWLEDGE
#endif

#define LIBSIMPLE_CHAR_SYN '\x16'
#ifndef CHAR_SYN
# define CHAR_SYN LIBSIMPLE_CHAR_SYN
#endif
#define LIBSIMPLE_CHAR_SYNCHRONOUS_IDLE LIBSIMPLE_CHAR_SYN
#ifndef CHAR_SYNCHRONOUS_IDLE
# define CHAR_SYNCHRONOUS_IDLE LIBSIMPLE_CHAR_SYNCHRONOUS_IDLE
#endif

#define LIBSIMPLE_CHAR_ETB '\x17'
#ifndef CHAR_ETB
# define CHAR_ETB LIBSIMPLE_CHAR_ETB
#endif
#define LIBSIMPLE_CHAR_END_OF_TRANSMISSION_BLOCK LIBSIMPLE_CHAR_ETB
#ifndef CHAR_END_OF_TRANSMISSION_BLOCK
# define CHAR_END_OF_TRANSMISSION_BLOCK LIBSIMPLE_CHAR_END_OF_TRANSMISSION_BLOCK
#endif

#define LIBSIMPLE_CHAR_CAN '\x18'
#ifndef CHAR_CAN
# define CHAR_CAN LIBSIMPLE_CHAR_CAN
#endif
#define LIBSIMPLE_CHAR_CANCEL LIBSIMPLE_CHAR_CAN
#ifndef CHAR_CANCEL
# define CHAR_CANCEL LIBSIMPLE_CHAR_CANCEL
#endif

#define LIBSIMPLE_CHAR_EM '\x19'
#ifndef CHAR_EM
# define CHAR_EM LIBSIMPLE_CHAR_EM
#endif
#define LIBSIMPLE_CHAR_END_OF_MEDIUM LIBSIMPLE_CHAR_EM
#ifndef CHAR_END_OF_MEDIUM
# define CHAR_END_OF_MEDIUM LIBSIMPLE_CHAR_END_OF_MEDIUM
#endif

#define LIBSIMPLE_CHAR_SUB '\x1A'
#ifndef CHAR_SUB
# define CHAR_SUB LIBSIMPLE_CHAR_SUB
#endif
#define LIBSIMPLE_CHAR_SUBSTITUTE LIBSIMPLE_CHAR_SUB
#ifndef CHAR_SUBSTITUTE
# define CHAR_SUBSTITUTE LIBSIMPLE_CHAR_SUBSTITUTE
#endif

#define LIBSIMPLE_CHAR_ESC '\x1B'
#ifndef CHAR_ESC
# define CHAR_ESC LIBSIMPLE_CHAR_ESC
#endif
#define LIBSIMPLE_CHAR_ESCAPE LIBSIMPLE_CHAR_ESC
#ifndef CHAR_ESCAPE
# define CHAR_ESCAPE LIBSIMPLE_CHAR_ESCAPE
#endif

#define LIBSIMPLE_CHAR_FS '\x1C'
#ifndef CHAR_FS
# define CHAR_FS LIBSIMPLE_CHAR_FS
#endif
#define LIBSIMPLE_CHAR_FILE_SEPARATOR LIBSIMPLE_CHAR_FS
#ifndef CHAR_FILE_SEPARATOR
# define CHAR_FILE_SEPARATOR LIBSIMPLE_CHAR_FILE_SEPARATOR
#endif

#define LIBSIMPLE_CHAR_GS '\x1D'
#ifndef CHAR_GS
# define CHAR_GS LIBSIMPLE_CHAR_GS
#endif
#define LIBSIMPLE_CHAR_GROUP_SEPARATOR LIBSIMPLE_CHAR_GS
#ifndef CHAR_GROUP_SEPARATOR
# define CHAR_GROUP_SEPARATOR LIBSIMPLE_CHAR_GROUP_SEPARATOR
#endif

#define LIBSIMPLE_CHAR_RS '\x1E'
#ifndef CHAR_RS
# define CHAR_RS LIBSIMPLE_CHAR_RS
#endif
#define LIBSIMPLE_CHAR_RECORD_SEPARATOR LIBSIMPLE_CHAR_RS
#ifndef CHAR_RECORD_SEPARATOR
# define CHAR_RECORD_SEPARATOR LIBSIMPLE_CHAR_RECORD_SEPARATOR
#endif

#define LIBSIMPLE_CHAR_US '\x1F'
#ifndef CHAR_US
# define CHAR_US LIBSIMPLE_CHAR_US
#endif
#define LIBSIMPLE_CHAR_UNIT_SEPARATOR LIBSIMPLE_CHAR_US
#ifndef CHAR_UNIT_SEPARATOR
# define CHAR_UNIT_SEPARATOR LIBSIMPLE_CHAR_UNIT_SEPARATOR
#endif

#define LIBSIMPLE_CHAR_SP '\x20'
#ifndef CHAR_SP
# define CHAR_SP LIBSIMPLE_CHAR_SP
#endif
#define LIBSIMPLE_CHAR_SPACE LIBSIMPLE_CHAR_SP
#ifndef CHAR_SPACE
# define CHAR_SPACE LIBSIMPLE_CHAR_SPACE
#endif

#define LIBSIMPLE_CHAR_DEL '\x7F'
#ifndef CHAR_DEL
# define CHAR_DEL LIBSIMPLE_CHAR_DEL
#endif
#define LIBSIMPLE_CHAR_DELETE LIBSIMPLE_CHAR_DEL
#ifndef CHAR_DELETE
# define CHAR_DELETE LIBSIMPLE_CHAR_DELETE
#endif


#define LIBSIMPLE_STR_CHAR_NUL "\x00"
#ifndef STR_CHAR_NUL
# define STR_CHAR_NUL LIBSIMPLE_STR_CHAR_NUL
#endif
#define LIBSIMPLE_STR_CHAR_NULL LIBSIMPLE_STR_CHAR_NUL
#ifndef STR_CHAR_NULL
# define STR_CHAR_NULL LIBSIMPLE_STR_CHAR_NULL
#endif

#define LIBSIMPLE_STR_CHAR_SOH "\x01"
#ifndef STR_CHAR_SOH
# define STR_CHAR_SOH LIBSIMPLE_STR_CHAR_SOH
#endif
#define LIBSIMPLE_STR_CHAR_START_OF_HEADING LIBSIMPLE_STR_CHAR_SOH
#ifndef STR_CHAR_START_OF_HEADING
# define STR_CHAR_START_OF_HEADING LIBSIMPLE_STR_CHAR_START_OF_HEADING
#endif

#define LIBSIMPLE_STR_CHAR_STX "\x02"
#ifndef STR_CHAR_STX
# define STR_CHAR_STX LIBSIMPLE_STR_CHAR_STX
#endif
#define LIBSIMPLE_STR_CHAR_START_OF_TEXT LIBSIMPLE_STR_CHAR_STX
#ifndef STR_CHAR_START_OF_TEXT
# define STR_CHAR_START_OF_TEXT LIBSIMPLE_STR_CHAR_START_OF_TEXT
#endif

#define LIBSIMPLE_STR_CHAR_ETX "\x03"
#ifndef STR_CHAR_ETX
# define STR_CHAR_ETX LIBSIMPLE_STR_CHAR_ETX
#endif
#define LIBSIMPLE_STR_CHAR_END_OF_TEXT LIBSIMPLE_STR_CHAR_ETX
#ifndef STR_CHAR_END_OF_TEXT
# define STR_CHAR_END_OF_TEXT LIBSIMPLE_STR_CHAR_END_OF_TEXT
#endif

#define LIBSIMPLE_STR_CHAR_EOT "\x04"
#ifndef STR_CHAR_EOT
# define STR_CHAR_EOT LIBSIMPLE_STR_CHAR_EOT
#endif
#define LIBSIMPLE_STR_CHAR_END_OF_TRANSMISSION LIBSIMPLE_STR_CHAR_EOT
#ifndef STR_CHAR_END_OF_TRANSMISSION
# define STR_CHAR_END_OF_TRANSMISSION LIBSIMPLE_STR_CHAR_END_OF_TRANSMISSION
#endif

#define LIBSIMPLE_STR_CHAR_ENQ "\x05"
#ifndef STR_CHAR_ENQ
# define STR_CHAR_ENQ LIBSIMPLE_STR_CHAR_ENQ
#endif
#define LIBSIMPLE_STR_CHAR_ENQUIRY LIBSIMPLE_STR_CHAR_ENQ
#ifndef STR_CHAR_ENQUIRY
# define STR_CHAR_ENQUIRY LIBSIMPLE_STR_CHAR_ENQUIRY
#endif

#define LIBSIMPLE_STR_CHAR_ACK "\x06"
#ifndef STR_CHAR_ACK
# define STR_CHAR_ACK LIBSIMPLE_STR_CHAR_ACK
#endif
#define LIBSIMPLE_STR_CHAR_ACKNOWLEDGE LIBSIMPLE_STR_CHAR_ACK
#ifndef STR_CHAR_ACKNOWLEDGE
# define STR_CHAR_ACKNOWLEDGE LIBSIMPLE_STR_CHAR_ACKNOWLEDGE
#endif

#define LIBSIMPLE_STR_CHAR_BEL "\x07"
#ifndef STR_CHAR_BEL
# define STR_CHAR_BEL LIBSIMPLE_STR_CHAR_BEL
#endif
#define LIBSIMPLE_STR_CHAR_BELL LIBSIMPLE_STR_CHAR_BEL
#ifndef STR_CHAR_BELL
# define STR_CHAR_BELL LIBSIMPLE_STR_CHAR_BELL
#endif

#define LIBSIMPLE_STR_CHAR_BS "\x08"
#ifndef STR_CHAR_BS
# define STR_CHAR_BS LIBSIMPLE_STR_CHAR_BS
#endif
#define LIBSIMPLE_STR_CHAR_BACKSPACE LIBSIMPLE_STR_CHAR_BS
#ifndef STR_CHAR_BACKSPACE
# define STR_CHAR_BACKSPACE LIBSIMPLE_STR_CHAR_BACKSPACE
#endif

#define LIBSIMPLE_STR_CHAR_HT "\x09"
#ifndef STR_CHAR_HT
# define STR_CHAR_HT LIBSIMPLE_STR_CHAR_HT
#endif
#define LIBSIMPLE_STR_CHAR_HORIZONTAL_TABULATION LIBSIMPLE_STR_CHAR_HT
#ifndef STR_CHAR_HORIZONTAL_TABULATION
# define STR_CHAR_HORIZONTAL_TABULATION LIBSIMPLE_STR_CHAR_HORIZONTAL_TABULATION
#endif

#define LIBSIMPLE_STR_CHAR_LF "\x0A"
#ifndef STR_CHAR_LF
# define STR_CHAR_LF LIBSIMPLE_STR_CHAR_LF
#endif
#define LIBSIMPLE_STR_CHAR_LINE_FEED LIBSIMPLE_STR_CHAR_LF
#ifndef STR_CHAR_LINE_FEED
# define STR_CHAR_LINE_FEED LIBSIMPLE_STR_CHAR_LINE_FEED
#endif

#define LIBSIMPLE_STR_CHAR_VT "\x0B"
#ifndef STR_CHAR_VT
# define STR_CHAR_VT LIBSIMPLE_STR_CHAR_VT
#endif
#define LIBSIMPLE_STR_CHAR_VERTICAL_TABULATION LIBSIMPLE_STR_CHAR_VT
#ifndef STR_CHAR_VERTICAL_TABULATION
# define STR_CHAR_VERTICAL_TABULATION LIBSIMPLE_STR_CHAR_VERTICAL_TABULATION
#endif

#define LIBSIMPLE_STR_CHAR_FF "\x0C"
#ifndef STR_CHAR_FF
# define STR_CHAR_FF LIBSIMPLE_STR_CHAR_FF
#endif
#define LIBSIMPLE_STR_CHAR_FORM_FEED LIBSIMPLE_STR_CHAR_FF
#ifndef STR_CHAR_FORM_FEED
# define STR_CHAR_FORM_FEED LIBSIMPLE_STR_CHAR_FORM_FEED
#endif

#define LIBSIMPLE_STR_CHAR_CR "\x0D"
#ifndef STR_CHAR_CR
# define STR_CHAR_CR LIBSIMPLE_STR_CHAR_CR
#endif
#define LIBSIMPLE_STR_CHAR_CARRIAGE_RETURN LIBSIMPLE_STR_CHAR_CR
#ifndef STR_CHAR_CARRIAGE_RETURN
# define STR_CHAR_CARRIAGE_RETURN LIBSIMPLE_STR_CHAR_CARRIAGE_RETURN
#endif

#define LIBSIMPLE_STR_CHAR_SO "\x0E"
#ifndef STR_CHAR_SO
# define STR_CHAR_SO LIBSIMPLE_STR_CHAR_SO
#endif
#define LIBSIMPLE_STR_CHAR_SHIFT_OUT LIBSIMPLE_STR_CHAR_SO
#ifndef STR_CHAR_SHIFT_OUT
# define STR_CHAR_SHIFT_OUT LIBSIMPLE_STR_CHAR_SHIFT_OUT
#endif

#define LIBSIMPLE_STR_CHAR_SI "\x0F"
#ifndef STR_CHAR_SI
# define STR_CHAR_SI LIBSIMPLE_STR_CHAR_SI
#endif
#define LIBSIMPLE_STR_CHAR_SHIFT_IN LIBSIMPLE_STR_CHAR_SI
#ifndef STR_CHAR_SHIFT_IN
# define STR_CHAR_SHIFT_IN LIBSIMPLE_STR_CHAR_SHIFT_IN
#endif

#define LIBSIMPLE_STR_CHAR_DLE "\x10"
#ifndef STR_CHAR_DLE
# define STR_CHAR_DLE LIBSIMPLE_STR_CHAR_DLE
#endif
#define LIBSIMPLE_STR_CHAR_DATA_LINK_ESCAPE LIBSIMPLE_STR_CHAR_DLE
#ifndef STR_CHAR_DATA_LINK_ESCAPE
# define STR_CHAR_DATA_LINK_ESCAPE LIBSIMPLE_STR_CHAR_DATA_LINK_ESCAPE
#endif

#define LIBSIMPLE_STR_CHAR_DC1 "\x11"
#ifndef STR_CHAR_DC1
# define STR_CHAR_DC1 LIBSIMPLE_STR_CHAR_DC1
#endif
#define LIBSIMPLE_STR_CHAR_DEVICE_CONTROL_1 LIBSIMPLE_STR_CHAR_DC1
#ifndef STR_CHAR_DEVICE_CONTROL_1
# define STR_CHAR_DEVICE_CONTROL_1 LIBSIMPLE_STR_CHAR_DEVICE_CONTROL_1
#endif

#define LIBSIMPLE_STR_CHAR_DC2 "\x12"
#ifndef STR_CHAR_DC2
# define STR_CHAR_DC2 LIBSIMPLE_STR_CHAR_DC2
#endif
#define LIBSIMPLE_STR_CHAR_DEVICE_CONTROL_2 LIBSIMPLE_STR_CHAR_DC2
#ifndef STR_CHAR_DEVICE_CONTROL_2
# define STR_CHAR_DEVICE_CONTROL_2 LIBSIMPLE_STR_CHAR_DEVICE_CONTROL_2
#endif

#define LIBSIMPLE_STR_CHAR_DC3 "\x13"
#ifndef STR_CHAR_DC3
# define STR_CHAR_DC3 LIBSIMPLE_STR_CHAR_DC3
#endif
#define LIBSIMPLE_STR_CHAR_DEVICE_CONTROL_3 LIBSIMPLE_STR_CHAR_DC3
#ifndef STR_CHAR_DEVICE_CONTROL_3
# define STR_CHAR_DEVICE_CONTROL_3 LIBSIMPLE_STR_CHAR_DEVICE_CONTROL_3
#endif

#define LIBSIMPLE_STR_CHAR_DC4 "\x14"
#ifndef STR_CHAR_DC4
# define STR_CHAR_DC4 LIBSIMPLE_STR_CHAR_DC4
#endif
#define LIBSIMPLE_STR_CHAR_DEVICE_CONTROL_4 LIBSIMPLE_STR_CHAR_DC4
#ifndef STR_CHAR_DEVICE_CONTROL_4
# define STR_CHAR_DEVICE_CONTROL_4 LIBSIMPLE_STR_CHAR_DEVICE_CONTROL_4
#endif

#define LIBSIMPLE_STR_CHAR_NAK "\x15"
#ifndef STR_CHAR_NAK
# define STR_CHAR_NAK LIBSIMPLE_STR_CHAR_NAK
#endif
#define LIBSIMPLE_STR_CHAR_NEGATIVE_ACKNOWLEDGE LIBSIMPLE_STR_CHAR_NAK
#ifndef STR_CHAR_NEGATIVE_ACKNOWLEDGE
# define STR_CHAR_NEGATIVE_ACKNOWLEDGE LIBSIMPLE_STR_CHAR_NEGATIVE_ACKNOWLEDGE
#endif

#define LIBSIMPLE_STR_CHAR_SYN "\x16"
#ifndef STR_CHAR_SYN
# define STR_CHAR_SYN LIBSIMPLE_STR_CHAR_SYN
#endif
#define LIBSIMPLE_STR_CHAR_SYNCHRONOUS_IDLE LIBSIMPLE_STR_CHAR_SYN
#ifndef STR_CHAR_SYNCHRONOUS_IDLE
# define STR_CHAR_SYNCHRONOUS_IDLE LIBSIMPLE_STR_CHAR_SYNCHRONOUS_IDLE
#endif

#define LIBSIMPLE_STR_CHAR_ETB "\x17"
#ifndef STR_CHAR_ETB
# define STR_CHAR_ETB LIBSIMPLE_STR_CHAR_ETB
#endif
#define LIBSIMPLE_STR_CHAR_END_OF_TRANSMISSION_BLOCK LIBSIMPLE_STR_CHAR_ETB
#ifndef STR_CHAR_END_OF_TRANSMISSION_BLOCK
# define STR_CHAR_END_OF_TRANSMISSION_BLOCK LIBSIMPLE_STR_CHAR_END_OF_TRANSMISSION_BLOCK
#endif

#define LIBSIMPLE_STR_CHAR_CAN "\x18"
#ifndef STR_CHAR_CAN
# define STR_CHAR_CAN LIBSIMPLE_STR_CHAR_CAN
#endif
#define LIBSIMPLE_STR_CHAR_CANCEL LIBSIMPLE_STR_CHAR_CAN
#ifndef STR_CHAR_CANCEL
# define STR_CHAR_CANCEL LIBSIMPLE_STR_CHAR_CANCEL
#endif

#define LIBSIMPLE_STR_CHAR_EM "\x19"
#ifndef STR_CHAR_EM
# define STR_CHAR_EM LIBSIMPLE_STR_CHAR_EM
#endif
#define LIBSIMPLE_STR_CHAR_END_OF_MEDIUM LIBSIMPLE_STR_CHAR_EM
#ifndef STR_CHAR_END_OF_MEDIUM
# define STR_CHAR_END_OF_MEDIUM LIBSIMPLE_STR_CHAR_END_OF_MEDIUM
#endif

#define LIBSIMPLE_STR_CHAR_SUB "\x1A"
#ifndef STR_CHAR_SUB
# define STR_CHAR_SUB LIBSIMPLE_STR_CHAR_SUB
#endif
#define LIBSIMPLE_STR_CHAR_SUBSTITUTE LIBSIMPLE_STR_CHAR_SUB
#ifndef STR_CHAR_SUBSTITUTE
# define STR_CHAR_SUBSTITUTE LIBSIMPLE_STR_CHAR_SUBSTITUTE
#endif

#define LIBSIMPLE_STR_CHAR_ESC "\x1B"
#ifndef STR_CHAR_ESC
# define STR_CHAR_ESC LIBSIMPLE_STR_CHAR_ESC
#endif
#define LIBSIMPLE_STR_CHAR_ESCAPE LIBSIMPLE_STR_CHAR_ESC
#ifndef STR_CHAR_ESCAPE
# define STR_CHAR_ESCAPE LIBSIMPLE_STR_CHAR_ESCAPE
#endif

#define LIBSIMPLE_STR_CHAR_FS "\x1C"
#ifndef STR_CHAR_FS
# define STR_CHAR_FS LIBSIMPLE_STR_CHAR_FS
#endif
#define LIBSIMPLE_STR_CHAR_FILE_SEPARATOR LIBSIMPLE_STR_CHAR_FS
#ifndef STR_CHAR_FILE_SEPARATOR
# define STR_CHAR_FILE_SEPARATOR LIBSIMPLE_STR_CHAR_FILE_SEPARATOR
#endif

#define LIBSIMPLE_STR_CHAR_GS "\x1D"
#ifndef STR_CHAR_GS
# define STR_CHAR_GS LIBSIMPLE_STR_CHAR_GS
#endif
#define LIBSIMPLE_STR_CHAR_GROUP_SEPARATOR LIBSIMPLE_STR_CHAR_GS
#ifndef STR_CHAR_GROUP_SEPARATOR
# define STR_CHAR_GROUP_SEPARATOR LIBSIMPLE_STR_CHAR_GROUP_SEPARATOR
#endif

#define LIBSIMPLE_STR_CHAR_RS "\x1E"
#ifndef STR_CHAR_RS
# define STR_CHAR_RS LIBSIMPLE_STR_CHAR_RS
#endif
#define LIBSIMPLE_STR_CHAR_RECORD_SEPARATOR LIBSIMPLE_STR_CHAR_RS
#ifndef STR_CHAR_RECORD_SEPARATOR
# define STR_CHAR_RECORD_SEPARATOR LIBSIMPLE_STR_CHAR_RECORD_SEPARATOR
#endif

#define LIBSIMPLE_STR_CHAR_US "\x1F"
#ifndef STR_CHAR_US
# define STR_CHAR_US LIBSIMPLE_STR_CHAR_US
#endif
#define LIBSIMPLE_STR_CHAR_UNIT_SEPARATOR LIBSIMPLE_STR_CHAR_US
#ifndef STR_CHAR_UNIT_SEPARATOR
# define STR_CHAR_UNIT_SEPARATOR LIBSIMPLE_STR_CHAR_UNIT_SEPARATOR
#endif

#define LIBSIMPLE_STR_CHAR_SP "\x20"
#ifndef STR_CHAR_SP
# define STR_CHAR_SP LIBSIMPLE_STR_CHAR_SP
#endif
#define LIBSIMPLE_STR_CHAR_SPACE LIBSIMPLE_STR_CHAR_SP
#ifndef STR_CHAR_SPACE
# define STR_CHAR_SPACE LIBSIMPLE_STR_CHAR_SPACE
#endif

#define LIBSIMPLE_STR_CHAR_DEL "\x7F"
#ifndef STR_CHAR_DEL
# define STR_CHAR_DEL LIBSIMPLE_STR_CHAR_DEL
#endif
#define LIBSIMPLE_STR_CHAR_DELETE LIBSIMPLE_STR_CHAR_DEL
#ifndef STR_CHAR_DELETE
# define STR_CHAR_DELETE LIBSIMPLE_STR_CHAR_DELETE
#endif


#define LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, ABBR, FULL, NAME)\
	X(LIBSIMPLE_CHAR_##ABBR, LIBSIMPLE_STR_CHAR_##ABBR, #ABBR, ABBR, #FULL, FULL, NAME)

#define LIBSIMPLE_LIST_ASCII_CONTROL_CHARS(X, D)\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, NUL, NULL, "null") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, SOH, START_OF_HEADING, "start of heading") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, STX, START_OF_TEXT, "start of text") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, ETX, END_OF_TEXT, "end of text") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, EOT, END_OF_TRANSMISSION, "end of transmission") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, ENQ, ENQUIRY, "enquiry") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, ACK, ACKNOWLEDGE, "acknowledge") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, BEL, BELL, "bell") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, BS, BACKSPACE, "backspace") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, HT, HORIZONTAL_TABULATION, "horizontal tabulation") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, LF, LINE_FEED, "line feed") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, VT, VERTICAL_TABULATION, "vertical tabulation") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, FF, FORM_FEED, "form feed") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, CR, CARRIAGE_RETURN, "carriage return") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, SO, SHIFT_OUT, "shift out") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, SI, SHIFT_IN, "shift in") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, DLE, DATA_LINK_ESCAPE, "data link escape") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, DC1, DEVICE_CONTROL_1, "device control 1") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, DC2, DEVICE_CONTROL_2, "device control 2") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, DC3, DEVICE_CONTROL_3, "device control 3") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, DC4, DEVICE_CONTROL_4, "device control 4") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, NAK, NEGATIVE_ACKNOWLEDGE, "negative acknowledge") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, SYN, SYNCHRONOUS_IDLE, "synchronous idle") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, ETB, END_OF_TRANSMISSION_BLOCK, "end of transmission block") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, CAN, CANCEL, "cancel") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, EM, END_OF_MEDIUM, "end of medium") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, SUB, SUBSTITUTE, "substitute") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, ESC, ESCAPE, "escape") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, FS, FILE_SEPARATOR, "file separator") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, GS, GROUP_SEPARATOR, "group separator") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, RS, RECORD_SEPARATOR, "record separator") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, US, UNIT_SEPARATOR, "unit separator") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, SP, SPACE, "space") D\
	LIBSIMPLE_LIST_ASCII_CONTROL_CHARS__(X, DEL, DELETE, "delete")
