.TH LIBSIMPLE_MEMSCAN_INV 3 libsimple
.SH NAME
libsimple_memscan_inv \- skip byte in memory

.SH SYNOPSIS
.nf
#include <libsimple.h>

void *libsimple_memscan_inv(const void *\fIs\fP, int \fIc\fP, size_t \fIn\fP);

#ifndef memscan_inv
# define memscan_inv libsimple_memscan_inv
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_memscan_inv ()
function scans the memory segment
.IR s ,
with the size
.IR n ,
for the first occurence of any byte
other than
.I c
(it is converted to a
.BR char ).
If no such character exist in the memory
segment, the memory segment's end is returned.
.PP
The comparison is case-sensitive.

.SH RETURN VALUE
The
.BR libsimple_memscan_inv ()
function returns the pointer
.I s
with a minimal offset such that
.IR *r!=c ,
where
.I r
is the returned pointer.
If no such offset exists,
.I &r[n]
is returned.

.SH ERRORS
The
.BR libsimple_memscan_inv ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_memscan_inv ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_memscan_inv ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_memscan_inv ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_memscan (3),
.BR libsimple_memchr_inv (3),
.BR libsimple_memcasescan_inv (3),
.BR libsimple_memrchr_inv (3),
.BR libsimple_rawmemchr_inv (3),
.BR libsimple_strnchrnul_inv (3),
.BR libsimple_strchrnul_inv (3)
