.TH LIBSIMPLE_STRENDS 3 libsimple
.SH NAME
libsimple_strends \- check the beginning of a string

.SH SYNOPSIS
.nf
#include <libsimple.h>

int libsimple_strends(const char *\fIs\fP, const char *\fIt\fP);

#ifndef strends
# define strends libsimple_strends
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strends ()
function checks whether the string
.I s
ends with the string
.IR t .
.PP
The comparison is case-sensitive.

.SH RETURN VALUE
The
.BR libsimple_strends ()
function returns 1 if the string
.I s
ends with the string
.IR t ,
otherwise it returns 0.

.SH ERRORS
The
.BR libsimple_strends ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strends ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strends ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strends ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH HISTORY
libsimple 1.0

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_strcaseends (3),
.BR libsimple_strstarts (3),
.BR libsimple_strrstr (3),
.BR libsimple_strnends (3),
.BR libsimple_memends (3)
