.TH LIBSIMPLE_STRCASEEQLEN 3 libsimple
.SH NAME
libsimple_strcaseeqlen \- check initial commonality

.SH SYNOPSIS
.nf
#include <libsimple.h>

size_t libsimple_strcaseeqlen(const char *\fIa\fP, const char *\fIb\fP);

#ifndef strcaseeqlen
# define strcaseeqlen libsimple_strcaseeqlen
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strcaseeqlen ()
function scans the number of bytes the string
.I a
have in common the string
.I b
at their beginnings.
.PP
The comparison is case-insensitive.

.SH RETURN VALUE
The
.BR libsimple_strcaseeqlen ()
function returns the number of bytes
.I a
and
.I b
have in common at their beginnings.

.SH ERRORS
The
.BR libsimple_strcaseeqlen ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strcaseeqlen ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strcaseeqlen ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strcaseeqlen ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_strcaseeq (3),
.BR libsimple_streqlen (3),
.BR libsimple_strrcaseeqlen (3),
.BR libsimple_strncaseeqlen (3),
.BR libsimple_memcaseeqlen (3)
