.TH LIBSIMPLE_VVALLOCZN 3 2018-11-03 libsimple
.SH NAME
libsimple_vvalloczn \- allocate optionally initialised memory with page size alignment
.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline void *libsimple_vvalloczn(int \fIclear\fP, size_t \fIn\fP, va_list \fIap\fP);
static inline void *libsimple_envvalloczn(int \fIstatus\fP, int \fIclear\fP, size_t \fIn\fP, va_list \fIap\fP);
static inline void *libsimple_evvalloczn(int \fIclear\fP, size_t \fIn\fP, va_list \fIap\fP);
static inline void *libsimple_valloczn(int \fIclear\fP, size_t \fIn\fP, ..., /* (size_t)0 */);
static inline void *libsimple_envalloczn(int \fIstatus\fP, int \fIclear\fP, size_t \fIn\fP, ..., /* (size_t)0 */);
static inline void *libsimple_evalloczn(int \fIclear\fP, size_t \fIn\fP, ..., /* (size_t)0 */);

#ifndef vvalloczn
# define vvalloczn libsimple_vvalloczn
#endif
#ifndef envvalloczn
# define envvalloczn libsimple_envvalloczn
#endif
#ifndef evvalloczn
# define evvalloczn libsimple_evvalloczn
#endif
#ifndef valloczn
# define valloczn libsimple_valloczn
#endif
#ifndef envalloczn
# define envalloczn libsimple_envalloczn
#endif
#ifndef evalloczn
# define evalloczn libsimple_evalloczn
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_valloczn (),
.BR libsimple_envalloczn (),
and
.BR libsimple_evalloczn ()
functions allocate
.I N
bytes to the heap and return a pointer with an
alignment of the page size
to the allocated memory, where
.I N
is the product of
.I n
and all following arguments (which should have the type
.BR size_t )
up to the first 0;
.I n
must not be 0. The memory will be initialised
with zeroes if
.I clear
is a non-zero value. The function
.BR free (3)
shall be called with the returned pointer as
input when the allocated memory is no longer needed.
.PP
The
.BR libsimple_envalloczn ()
and
.BR libsimple_evalloczn ()
functions will terminate the process if the memory
cannot be allocated, by calling the
.BR libsimple_enprintf ()
and
.BR libsimple_eprintf ()
functions, respectively.
On failure, the process's exit value will be
.I status
if the
.BR libsimple_envalloczn ()
function is used or
.IR libsimple_default_failure_exit (3)
if the
.BR libsimple_evalloczn ()
function is used.
.PP
The
.BR libsimple_vvalloczn (),
.BR libsimple_envvalloczn (),
and
.BR libsimple_evvalloczn ()
functions are versions of the
.BR libsimple_valloczn (),
.BR libsimple_envalloczn (),
and
.BR libsimple_evalloczn (),
respectively, that use
.B va_list
instead of variadic arguments.
.SH RETURN VALUE
The
.BR libsimple_vvalloczn (),
.BR libsimple_envvalloczn (),
.BR libsimple_evvalloczn (),
.BR libsimple_valloczn (),
.BR libsimple_envalloczn (),
and
.BR libsimple_evalloczn ()
functions return a pointer to the allocated memory
upon success completion; otherwise the
.BR libsimple_vvalloczn ()
and
.BR libsimple_valloczn ()
functions return
.B NULL
and set
.I errno
it indicate the error, and the
.BR libsimple_envvalloczn (),
.BR libsimple_evvalloczn (),
.BR libsimple_envalloczn (),
and
.BR libsimple_evalloczn ()
functions terminated the process.
.SH ERRORS
The
.BR libsimple_vvalloczn (),
.BR libsimple_valloczn ()
function will fail if:
.TP
.B EINVAL
.I n
is 0.
.TP
.B ENOMEM
Enough memory could not be allocated.
.PP
The
.BR libsimple_envvalloczn (),
.BR libsimple_evvalloczn (),
.BR libsimple_envalloczn (),
and
.BR libsimple_evalloczn ()
functions will terminate the process on failure.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_vvalloczn (),
.br
.BR libsimple_envvalloczn (),
.br
.BR libsimple_evvalloczn (),
.br
.BR libsimple_valloczn (),
.br
.BR libsimple_envalloczn (),
.br
.BR libsimple_evalloczn ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_vvalloczn (),
.br
.BR libsimple_envvalloczn (),
.br
.BR libsimple_evvalloczn (),
.br
.BR libsimple_valloczn (),
.br
.BR libsimple_envalloczn (),
.br
.BR libsimple_evalloczn ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_vvalloczn (),
.br
.BR libsimple_envvalloczn (),
.br
.BR libsimple_evvalloczn (),
.br
.BR libsimple_valloczn (),
.br
.BR libsimple_envalloczn (),
.br
.BR libsimple_evalloczn ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
The GNU implementation of
.BR valloc (3)
is \(dqMT-Unsafe init\(dq.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_enmalloc (3),
.BR libsimple_mallocz (3),
.BR libsimple_vmallocn (3),
.BR libsimple_vmalloczn (3),
.BR libsimple_encalloc (3),
.BR libsimple_vcallocn (3),
.BR libsimple_enrealloc (3),
.BR libsimple_vreallocn (3),
.BR libsimple_memalign (3),
.BR libsimple_memalignz (3),
.BR libsimple_vmemalignn (3),
.BR libsimple_vmemalignzn (3),
.BR libsimple_enposix_memalign (3),
.BR libsimple_posix_memalignz (3),
.BR libsimple_vposix_memalignn (3),
.BR libsimple_vposix_memalignzn (3),
.BR libsimple_enaligned_alloc (3),
.BR libsimple_aligned_allocz (3),
.BR libsimple_valigned_allocn (3),
.BR libsimple_valigned_alloczn (3),
.BR libsimple_pvalloc (3),
.BR libsimple_pvallocz (3),
.BR libsimple_vpvallocn (3),
.BR libsimple_vpvalloczn (3),
.BR libsimple_valloc (3),
.BR libsimple_vallocz (3),
.BR libsimple_vvallocn (3),
.BR libsimple_vmemalloc (3),
.BR libsimple_varrayalloc (3)
