.TH LIBSIMPLE_STREND 3 libsimple
.SH NAME
libsimple_strend \- find a character in a string

.SH SYNOPSIS
.nf
#include <libsimple.h>

inline char *libsimple_strend(const char *\fIs\fP);

#ifndef strend
# define strend libsimple_strend
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strend ()
function scans the string
.I s
for its end.

.SH RETURN VALUE
The
.BR libsimple_strend ()
function returns the pointer
.I s
with an offset such that
.IR !*r ,
where
.I r
is the returned pointer.

.SH ERRORS
The
.BR libsimple_strend ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strend ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strend ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strend ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH HISTORY
libsimple 1.0

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_strchrnul (3),
.BR libsimple_strnend (3),
.BR strchr (3)
