.TH LIBSIMPLE_MEMSCAN 3 libsimple
.SH NAME
libsimple_memscan \- find byte in memory

.SH SYNOPSIS
.nf
#include <libsimple.h>

void *libsimple_memscan(const void *\fIs\fP, int \fIc\fP, size_t \fIn\fP);

#ifndef memscan
# define memscan libsimple_memscan
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_memscan ()
function scans the memory segment
.IR s ,
with the size
.IR n ,
for the first occurence of the byte
.I c
(it is converted to a
.BR char ).
If no such character exist in the memory
segment, the memory segment's end is returned.
.PP
The comparison is case-sensitive.

.SH RETURN VALUE
The
.BR libsimple_memscan ()
function returns the pointer
.I s
with a minimal offset such that
.IR *r==c ,
where
.I r
is the returned pointer.
If no such offset exists,
.I &r[n]
is returned.

.SH ERRORS
The
.BR libsimple_memscan ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_memscan ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_memscan ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_memscan ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_memscan_inv (3),
.BR libsimple_memcasescan (3),
.BR libsimple_memrchr (3),
.BR libsimple_rawmemchr (3),
.BR libsimple_memmem (3),
.BR libsimple_strnchrnul (3),
.BR libsimple_strchrnul (3),
.BR memchr (3)
