.TH LIBSIMPLE_MEMRCASEMEM 3 libsimple
.SH NAME
libsimple_memrcasemem \- find byte string in memory

.SH SYNOPSIS
.nf
#include <libsimple.h>

void *libsimple_memrcasemem(const void *\fIhaystack\fP, size_t \fInhaystack\fP, const void *\fIneedle\fP, size_t \fInneedle\fP);

#ifndef memrcasemem
# define memrcasemem libsimple_memrcasemem
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_memrcasemem ()
function scans the memory segment
.IR haystack ,
with the size
.IR nhaystack ,
for the last occurence of the byte string
.I needle
with the size
.IR nneedle .
.PP
The comparison is case-insensitive.

.SH RETURN VALUE
The
.BR libsimple_memrcasemem ()
function returns the pointer
.I s
with a maximal offset such that
.IR !memcasecmp(r,needle,nneedle) ,
where
.I r
is the returned pointer.
If no such offset exists,
.B NULL
is returned.

.SH ERRORS
The
.BR libsimple_memrcasemem ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_memrcasemem ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_memrcasemem ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_memrcasemem ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH HISTORY
libsimple 1.1

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_memrmem (3),
.BR libsimple_memcasemem (3),
.BR libsimple_memrcasechr (3),
.BR libsimple_strrncasestr (3),
.BR libsimple_strrcasestr (3)
