.TH LIBSIMPLE_STRREQLEN 3 2018-10-23 libsimple
.SH NAME
libsimple_strreqlen \- check terminal commonality
.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline size_t libsimple_strreqlen(const char *\fIa\fP, const char *\fIb\fP);

#ifndef strreqlen
# define strreqlen libsimple_strreqlen
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_strreqlen ()
function scans the number of bytes the string
.I a
have in common the string
.I b
at their ends.
.PP
The comparison is case-sensitive.
.SH RETURN VALUE
The
.BR libsimple_strreqlen ()
function returns the number of bytes
.I a
and
.I b
have in common at their ends.
.SH ERRORS
The
.BR libsimple_strreqlen ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strreqlen ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strreqlen ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strreqlen ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_strreqlen (3),
.BR libsimple_streqlen (3),
.BR libsimple_strrneqlen (3),
.BR libsimple_memreqlen (3)
