.TH LIBSIMPLE_STREQNUL 3 2018-10-23 libsimple
.SH NAME
libsimple_streqnul \- compare two strings
.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline int libsimple_streqnul(const char *\fIa\fP, const char *\fIb\fP);

#ifndef streqnul
# define streqnul libsimple_streqnul
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_streqnul ()
function compares the strings
.I a
and
.IR b ,
both of which may be
.BR NULL .
.PP
The comparison is case-sensitive.
.SH RETURN VALUE
The
.BR libsimple_streqnul ()
function returns 1 if the strings are equals,
otherwise it returns 0.
.SH ERRORS
The
.BR libsimple_streqnul ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_streqnul ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_streqnul ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_streqnul ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_streq (3),
.BR libsimple_strcaseeqnul (3),
.BR libsimple_strcmpnul (3),
.BR libsimple_strneqnul (3),
.BR libsimple_memeq (3),
.BR strcmp (3)
