.TH LIBSIMPLE_STRNCASECHR 3 libsimple
.SH NAME
libsimple_strncasechr \- find a character in a string

.SH SYNOPSIS
.nf
#include <libsimple.h>

char *libsimple_strncasechr(const char *\fIs\fP, int \fIc\fP, size_t \fIn\fP);

#ifndef strncasechr
# define strncasechr libsimple_strncasechr
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strncasechr ()
function scans the string
.IR s ,
truncated to
.I n
bytes unless it is shorter,
for the first occurence of the character
.I c
(it is converted to a
.BR char ).
If no such character exist in the string,
the string's end is returned.
.PP
The comparison is case-insensitive.

.SH RETURN VALUE
The
.BR libsimple_strncasechr ()
function returns the pointer
.I s
with a minimal offset such that
.IR tolower(*r)==tolower(c) ,
where
.I r
is the returned pointer, if no such
offset less than
.I n
exists, it returns
.BR NULL .

.SH ERRORS
The
.BR libsimple_strncasechr ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strncasechr ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strncasechr ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strncasechr ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_strncasechr_inv (3),
.BR libsimple_strncasechrnul (3),
.BR libsimple_strrncasechr (3),
.BR libsimple_strnchr (3),
.BR libsimple_strcasechr (3),
.BR libsimple_memcasechr (3)
