.TH LIBSIMPLE_STRNEND 3 libsimple
.SH NAME
libsimple_strnend \- find a character in a string

.SH SYNOPSIS
.nf
#include <libsimple.h>

inline char *libsimple_strnend(const char *\fIs\fP, size_t \fIn\fP);

#ifndef strnend
# define strnend libsimple_strnend
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strnend ()
function scans the string
.IR s ,
truncated to
.I n
bytes unless it is shorter,
for its end.

.SH RETURN VALUE
The
.BR libsimple_strnend ()
function returns the pointer
.I s
with an offset such that
.IR !*r ,
where
.I r
is the returned pointer. However,
if no such offset less than
.I n
exists,
.I &s[n]
is returned.

.SH ERRORS
The
.BR libsimple_strnend ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strnend ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strnend ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strnend ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH HISTORY
libsimple 1.1

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_strnchrnul (3),
.BR libsimple_strnchr (3),
.BR libsimple_strend (3)
