.TH LIBSIMPLE_STRREPLACE 3 libsimple
.SH NAME
libsimple_strreplace \- replace characters in a string

.SH SYNOPSIS
.nf
#include <libsimple.h>

inline char *libsimple_strreplace(char *\fIs\fP, int \fIold\fP, int \fInew\fP);

#ifndef strreplace
# define strreplace libsimple_strreplace
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strreplace ()
function replaces all instances of the character
.I old
(it is converted to a
.BR char )
in the string
.I s
with the character
.IR new .
.PP
The comparison is case-sensitive.

.SH RETURN VALUE
The
.BR libsimple_strreplace ()
function returns the end of
.IR s ,
that is
.I &s[strlen(s)]
(as evaluated before the function call).

.SH ERRORS
The
.BR libsimple_strreplace ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strreplace ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strreplace ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strreplace ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH HISTORY
libsimple 1.1

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_strtolower (3),
.BR libsimple_strtoupper (3),
.BR libsimple_strnreplace (3),
.BR libsimple_memreplace (3)
