.TH LIBSIMPLE_STPNMOVE 3 2018-11-16 libsimple
.SH NAME
libsimple_stpnmove \- move a string within an array of bytes
.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline void *libsimple_stpnmove(void *\fIdest\fP, const void *\fIsrc\fP, size_t \fIn\fP);

#ifndef stpnmove
# define stpnmove libsimple_stpnmove
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_stpnmove ()
function copies the first
.I n
bytes of the string, including the
NUL byte that terminates it (if any),
.I src
into
.IR dest .
The arrays may overlap.
.SH RETURN VALUE
The
.BR libsimple_stpnmove ()
function returns the pointer
.I dest
with the offset of the length of string
.I str
(the address of the copied NUL byte in
.I dest
or
.I &dest[n]
if no NUL byte was copied).
.SH ERRORS
The
.BR libsimple_stpnmove ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_stpnmove ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_stpnmove ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_stpnmove ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_strnmove (3),
.BR libsimple_stpmove (3),
.BR libsimple_mempmove (3),
.BR libsimple_strncmove (3),
.BR stpncpy (3),
.BR memmove (3)
