.TH LIBSIMPLE_STRCASECHR_INV 3 libsimple
.SH NAME
libsimple_strcasechr_inv \- find a different character in a string

.SH SYNOPSIS
.nf
#include <libsimple.h>

char *libsimple_strcasechr_inv(const char *\fIs\fP, int \fIc\fP);

#ifndef strcasechr_inv
# define strcasechr_inv libsimple_strcasechr_inv
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strcasechr_inv ()
function scans the string
.I s
for the first occurence of any character
other than
.I c
(it is converted to a
.BR char ).
If no such character exist in the string,
the string's end is returned.
.PP
The comparison is case-insensitive.

.SH RETURN VALUE
The
.BR libsimple_strcasechr_inv ()
function returns the pointer
.I s
with a minimal offset such that
.IR tolower(*r)!=tolower(c) ,
where
.I r
is the returned pointer, if no such
offset exists, it returns
.BR NULL .

.SH ERRORS
The
.BR libsimple_strcasechr_inv ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strcasechr_inv ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strcasechr_inv ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strcasechr_inv ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_strcasechr (3),
.BR libsimple_strchr_inv (3),
.BR libsimple_strcasechrnul_inv (3),
.BR libsimple_strrcasechr_inv (3),
.BR libsimple_strncasechr_inv (3),
.BR libsimple_memcasechr_inv (3)
