.TH LIBSIMPLE_RAWMEMELEM 3 2018-11-24 libsimple
.SH NAME
libsimple_rawmemelem \- find aligned byte string in memory
.SH SYNOPSIS
.nf
#include <libsimple.h>

void *libsimple_rawmemelem(const void *\fIhaystack\fP, const void *\fIneedle\fP, size_t \fInneedle\fP);

#ifndef rawmemelem
# define rawmemelem libsimple_rawmemelem
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_rawmemelem ()
function scans the memory segment
.IR haystack ,
for the first occurence of the byte string
.I needle
with the size
.IR nneedle ,
and with an offset equivalent to zero modulo
.IR nneedle .
.PP
The
.BR libsimple_rawmemelem ()
function assumes there is at least one
occurence, its behaviour is undefined
if this is not the case.
.PP
The comparison is case-sensitive.
.SH RETURN VALUE
The
.BR libsimple_rawmemelem ()
function returns the pointer
.I s
with a minimal offset such that
.IR !memcmp(r,needle,nneedle) ,
where
.I r
is the returned pointer, and such that
the offset is equivalent to zero modulo
.IR nneedle .
If no such offset exists, the behaviour is undefined.
.SH ERRORS
The
.BR libsimple_rawmemelem ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_rawmemelem ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_rawmemelem ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_rawmemelem ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_rawmemelem_inv (3),
.BR libsimple_rawmemrelem (3),
.BR libsimple_memelem (3),
.BR libsimple_rawmemchr (3)
