.TH LIBSIMPLE_STREQ 3 libsimple
.SH NAME
libsimple_streq \- compare two strings

.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline int libsimple_streq(const char *\fIa\fP, const char *\fIb\fP);

#ifndef streq
# define streq libsimple_streq
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_streq ()
function compares the strings
.I a
and
.IR b ,
neither of which may be
.BR NULL .
.PP
The comparison is case-sensitive.

.SH RETURN VALUE
The
.BR libsimple_streq ()
function returns 1 if the strings are equals,
otherwise it returns 0.

.SH ERRORS
The
.BR libsimple_streq ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_streq ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_streq ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_streq ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_streqnul (3),
.BR libsimple_strcaseeq (3),
.BR libsimple_streqlen (3),
.BR libsimple_strneq (3),
.BR libsimple_memeq (3),
.BR strcmp (3)
