.TH LIBSIMPLE_STRNCHRNUL 3 libsimple
.SH NAME
libsimple_strnchrnul \- find a character in a string

.SH SYNOPSIS
.nf
#include <libsimple.h>

char *libsimple_strnchrnul(const char *\fIs\fP, int \fIc\fP, size_t \fIn\fP);

#ifndef strnchrnul
# define strnchrnul libsimple_strnchrnul
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strnchrnul ()
function scans the string
.IR s ,
truncated to
.I n
bytes unless it is shorter,
for the first occurence of the character
.I c
(it is converted to a
.BR char ).
If no such character exist in the string,
the string's end is returned.
.PP
The comparison is case-sensitive.

.SH RETURN VALUE
The
.BR libsimple_strnchrnul ()
function returns the pointer
.I s
with a minimal offset such that
.IR *r==c||!*r ,
where
.I r
is the returned pointer. However if no such
offset less than
.I n
exists,
.B NULL
is returned.

.SH ERRORS
The
.BR libsimple_strnchrnul ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strnchrnul ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strnchrnul ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strnchrnul ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None. I promise!

.SH SEE ALSO
.BR libsimple_strnchrnul_inv (3),
.BR libsimple_strncasechrnul (3),
.BR libsimple_strnchr (3),
.BR libsimple_strnend (3),
.BR libsimple_strchrnul (3),
.BR libsimple_memscan (3)
