.TH LIBSIMPLE_LOCALTIME 3 libsimple
.SH NAME
libsimple_localtime \- get the current local time with leap second adjustment

.SH SYNOPSIS
.nf
#include <libsimple.h>

int libsimple_localtime(struct tm *\fItm\fP, struct timespec *\fIts\fP);
static inline void libsimple_enlocaltime(int \fIstatus\fPstruct tm *\fItm\fP, struct timespec *\fIts\fP);
static inline void libsimple_elocaltime(struct tm *\fItm\fP, struct timespec *\fIts\fP);
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_localtime (),
.BR libsimple_enlocaltime (),
and
.BR libsimple_elocaltime ()
functions get the current local time, with adjustments
for leap seconds insertions and deletions.
.PP
The
.BR libsimple_enlocaltime ()
and
.BR libsimple_elocaltime ()
functions will terminate the process on failure.
On failure, the process's exit value will be
.I status
if the
.BR libsimple_enlocaltime ()
function is used or
.IR libsimple_default_failure_exit (3)
if the
.BR libsimple_elocaltime ()
fucntion is used.
.PP
The local time is stored in
.IR *tm ,
and the POSIX time (not timezone adjusted),
with leap second adjustments, is stored in
.I *ts
unless
.I ts
is
.IR NULL .
.I tm
may
.I not
be
.RI NULL .

.SH RETURN VALUE
The
.BR libsimple_localtime ()
function return a 0 upon successful completion;
otherwise the they return -1 and set
.I errno
to indicate the error. The
.BR libsimple_enlocaltime ()
and
.BR libsimple_elocaltime ()
functions terminate the processes on failure.

.SH ERRORS
The
.BR libsimple_localtime ()
function will fail for the reasons specified for the
.BR localtime_r (3)
function.
.PP
The
.BR libsimple_enlocaltime ()
and
.BR libsimple_elocaltime ()
functions will terminate the process on failure.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_localtime (),
.br
.BR libsimple_enlocaltime (),
.br
.BR libsimple_elocaltime ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_localtime (),
.br
.BR libsimple_enlocaltime (),
.br
.BR libsimple_elocaltime ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_localtime (),
.br
.BR libsimple_enlocaltime (),
.br
.BR libsimple_elocaltime ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_gmtime (3),
.BR ntp_adjtime (2),
.BR localtime_r (3)
