.TH LIBSIMPLE_MEMPSETELEM 3 2018-10-20 libsimple
.SH NAME
libsimple_mempsetelem \- fill an array with a value
.SH SYNOPSIS
.nf
#include <libsimple.h>

void *libsimple_mempsetelem(void *\fIbuf\fP, const void *\fIitem\fP, size_t \fIsize\fP, size_t \fInitems\fP);

#ifndef mempsetelem
# define mempsetelem libsimple_mempsetelem
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_mempsetelem ()
function fills the beginning of
.I buf
with
.I nitems
copies of the element
.I item
with the size
.IR size .
.SH RETURN VALUE
The
.BR libsimple_mempsetelem ()
function returns the pointer
.I buf
with the offset
.I nitems*size
(the byte where the copy stopped).
.SH ERRORS
The
.BR libsimple_mempsetelem ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_mempsetelem ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_mempsetelem ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_mempsetelem ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_memsetelem (3),
.BR libsimple_mempset (3)
