.TH LIBSIMPLE_MEMPMOVE 3 libsimple
.SH NAME
libsimple_mempmove \- move bytes within an array of bytes

.SH SYNOPSIS
.nf
#include <libsimple.h>

inline void *libsimple_mempmove(void *\fIdest\fP, const void *\fIsrc\fP, size_t \fIn\fP);

#ifndef mempmove
# define mempmove libsimple_mempmove
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_mempmove ()
function copies the first
.I n
bytes of
.I src
into
.IR dest .
The arrays may overlap.

.SH RETURN VALUE
The
.BR libsimple_mempmove ()
function returns the pointer
.I dest
with the offset
.I n
(the byte where the copy stopped).

.SH ERRORS
The
.BR libsimple_mempmove ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_mempmove ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_mempmove ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_mempmove ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_mempcpy (3),
.BR libsimple_mempset (3),
.BR libsimple_strmove (3),
.BR libsimple_stpmove (3),
.BR libsimple_strnmove (3),
.BR libsimple_stpnmove (3),
.BR libsimple_memcmove (3),
.BR memmove (3)
