.TH LIBSIMPLE_STRRCASECHR 3 libsimple
.SH NAME
libsimple_strrcasechr \- find a character in a string

.SH SYNOPSIS
.nf
#include <libsimple.h>

char *libsimple_strrcasechr(const char *\fIs\fP, int \fIc\fP);

#ifndef strrcasechr
# define strrcasechr libsimple_strrcasechr
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strrcasechr ()
function scans the string
.I s
for the last occurence of the character
.I c
(it is converted to a
.BR char ).
If no such character exist in the string,
the string's end is returned.
.PP
The comparison is case-insensitive.

.SH RETURN VALUE
The
.BR libsimple_strrcasechr ()
function returns the pointer
.I s
with a maximal offset such that
.IR tolower(*r)==tolower(c) ,
where
.I r
is the returned pointer, if no such
offset exists, it returns
.BR NULL .

.SH ERRORS
The
.BR libsimple_strrcasechr ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strrcasechr ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strrcasechr ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strrcasechr ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH HISTORY
libsimple 1.1

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_strrcasechr_inv (3),
.BR libsimple_strcasechr (3),
.BR libsimple_strrncasechr (3),
.BR libsimple_memrcasechr (3),
.BR strrchr (3)
