.TH LIBSIMPLE_STRCASECMPNUL 3 libsimple
.SH NAME
libsimple_strcasecmpnul \- compare two strings

.SH SYNOPSIS
.nf
#include <libsimple.h>

inline int libsimple_strcasecmpnul(const char *\fIa\fP, const char *\fIb\fP);

#ifndef strcasecmpnul
# define strcasecmpnul libsimple_strcasecmpnul
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strcasecmpnul ()
function compares the strings
.I a
and
.IR b ,
both of which may be
.BR NULL ,
which is treated as less than the empty string.
.PP
If one of the strings begins with the other string
but is longer, the longer string is treated as
greater than the shorter string.
.PP
The comparison is case-insensitive and made as
if the strings were converted to lowercase and as
.BR "unsigned char *" s.

.SH RETURN VALUE
The
.BR libsimple_strcasecmpnul ()
function returns a negative value if
.I a
is less than
.IR b ,
a positive value if
.I a
is greater than
.IR b ,
and 0 otherwise.

.SH ERRORS
The
.BR libsimple_strcasecmpnul ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strcasecmpnul ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strcasecmpnul ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strcasecmpnul ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH HISTORY
libsimple 1.0

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_strcmpnul (3),
.BR libsimple_strcaseeqnul (3),
.BR libsimple_strncasecmpnul (3),
.BR strcasecmp (3)
