.TH LIBSIMPLE_MEMCASEEQ 3 libsimple
.SH NAME
libsimple_memcaseeq \- check two memory segments for equality

.SH SYNOPSIS
.nf
#include <libsimple.h>

inline int libsimple_memcaseeq(const void *\fIa\fP, const void *\fIb\fP, size_t \fIn\fP);

#ifndef memcaseeq
# define memcaseeq libsimple_memcaseeq
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_memcaseeq ()
function checks whether the first
.I n
bytes of
.I a
and
.I b
are equal.
.PP
The comparison is case-insensitive.

.SH RETURN VALUE
The
.BR libsimple_memcaseeq ()
function returns 1 one if
.I a
and
.I b
are equal, with the possible exception if
their case, otherwise it returns 0.

.SH ERRORS
The
.BR libsimple_memcaseeq ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_memcaseeq ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_memcaseeq ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_memcaseeq ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_memeq (3),
.BR libsimple_memcaseeqlen (3),
.BR libsimple_memcasecmp (3),
.BR libsimple_strncaseeq (3),
.BR libsimple_strcaseeq (3)
