.TH LIBSIMPLE_MEMSETELEM 3 libsimple
.SH NAME
libsimple_memsetelem \- fill an array with a value

.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline void *libsimple_memsetelem(void *\fIbuf\fP, const void *\fIitem\fP, size_t \fIwidth\fP, size_t \fIn\fP);

#ifndef memsetelem
# define memsetelem libsimple_memsetelem
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_memsetelem ()
function fills the beginning of
.I buf
with
.I n
copies of the element
.I item
with the size
.IR width .

.SH RETURN VALUE
The
.BR libsimple_memsetelem ()
function returns the pointer
.IR buf .

.SH ERRORS
The
.BR libsimple_memsetelem ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_memsetelem ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_memsetelem ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_memsetelem ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_mempsetelem (3),
.BR memset (3)
