.TH LIBSIMPLE_VMEMALIGNZN 3 2018-11-03 libsimple
.SH NAME
libsimple_vmemalignzn \- allocate optionally initialised memory with custom alignment
.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline void *libsimple_vmemalignzn(int \fIclear\fP, size_t \fIalignment\fP, size_t \fIn\fP, va_list \fIap\fP);
static inline void *libsimple_envmemalignzn(int \fIstatus\fP, int \fIclear\fP, size_t \fIalignment\fP, size_t \fIn\fP, va_list \fIap\fP);
static inline void *libsimple_evmemalignzn(int \fIclear\fP, size_t \fIalignment\fP, size_t \fIn\fP, va_list \fIap\fP);
static inline void *libsimple_memalignzn(int \fIclear\fP, size_t \fIalignment\fP, size_t \fIn\fP, ..., /* (size_t)0 */);
static inline void *libsimple_enmemalignzn(int \fIstatus\fP, int \fIclear\fP, size_t \fIalignment\fP, size_t \fIn\fP, ..., /* (size_t)0 */);
static inline void *libsimple_ememalignzn(int \fIclear\fP, size_t \fIalignment\fP, size_t \fIn\fP, ..., /* (size_t)0 */);

#ifndef vmemalignzn
# define vmemalignzn libsimple_vmemalignzn
#endif
#ifndef envmemalignzn
# define envmemalignzn libsimple_envmemalignzn
#endif
#ifndef evmemalignzn
# define evmemalignzn libsimple_evmemalignzn
#endif
#ifndef memalignzn
# define memalignzn libsimple_memalignzn
#endif
#ifndef enmemalignzn
# define enmemalignzn libsimple_enmemalignzn
#endif
#ifndef ememalignzn
# define ememalignzn libsimple_ememalignzn
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_memalignzn (),
.BR libsimple_enmemalignzn (),
and
.BR libsimple_ememalignzn ()
functions allocate
.I N
bytes to the heap and return a pointer with an
alignment of
.I alignment
bytes to the allocated memory, where
.I N
is the product of
.I n
and all following arguments (which should have the type
.BR size_t )
up to the first 0;
.I n
must not be 0. The memory will be initialised
with zeroes if
.I clear
is a non-zero value. The function
.BR free (3)
shall be called with the returned pointer as
input when the allocated memory is no longer needed.
.PP
The
.BR libsimple_enmemalignzn ()
and
.BR libsimple_ememalignzn ()
functions will terminate the process if the memory
cannot be allocated, by calling the
.BR libsimple_enprintf ()
and
.BR libsimple_eprintf ()
functions, respectively.
On failure, the process's exit value will be
.I status
if the
.BR libsimple_enmemalignzn ()
function is used or
.IR libsimple_default_failure_exit (3)
if the
.BR libsimple_ememalignzn ()
function is used.
.PP
The
.BR libsimple_vmemalignzn (),
.BR libsimple_envmemalignzn (),
and
.BR libsimple_evmemalignzn ()
functions are versions of the
.BR libsimple_memalignzn (),
.BR libsimple_enmemalignzn (),
and
.BR libsimple_ememalignzn (),
respectively, that use
.B va_list
instead of variadic arguments.
.SH RETURN VALUE
The
.BR libsimple_vmemalignzn (),
.BR libsimple_envmemalignzn (),
.BR libsimple_evmemalignzn (),
.BR libsimple_memalignzn (),
.BR libsimple_enmemalignzn (),
and
.BR libsimple_ememalignzn ()
functions return a pointer to the allocated memory
upon success completion; otherwise the
.BR libsimple_vmemalignzn ()
and
.BR libsimple_memalignzn ()
functions return
.B NULL
and set
.I errno
it indicate the error, and the
.BR libsimple_envmemalignzn (),
.BR libsimple_evmemalignzn (),
.BR libsimple_enmemalignzn (),
and
.BR libsimple_ememalignzn ()
functions terminated the process.
.SH ERRORS
The
.BR libsimple_vmemalignzn (),
.BR libsimple_memalignzn ()
function will fail if:
.TP
.B EINVAL
.I n
is 0.
.TP
.B EINVAL
.I alignment
is not a power of two.
.TP
.B ENOMEM
Enough memory could not be allocated.
.PP
The
.BR libsimple_envmemalignzn (),
.BR libsimple_evmemalignzn (),
.BR libsimple_enmemalignzn (),
and
.BR libsimple_ememalignzn ()
functions will terminate the process on failure.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_vmemalignzn (),
.br
.BR libsimple_envmemalignzn (),
.br
.BR libsimple_evmemalignzn (),
.br
.BR libsimple_memalignzn (),
.br
.BR libsimple_enmemalignzn (),
.br
.BR libsimple_ememalignzn ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_vmemalignzn (),
.br
.BR libsimple_envmemalignzn (),
.br
.BR libsimple_evmemalignzn (),
.br
.BR libsimple_memalignzn (),
.br
.BR libsimple_enmemalignzn (),
.br
.BR libsimple_ememalignzn ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_vmemalignzn (),
.br
.BR libsimple_envmemalignzn (),
.br
.BR libsimple_evmemalignzn (),
.br
.BR libsimple_memalignzn (),
.br
.BR libsimple_enmemalignzn (),
.br
.BR libsimple_ememalignzn ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_enmalloc (3),
.BR libsimple_mallocz (3),
.BR libsimple_vmallocn (3),
.BR libsimple_vmalloczn (3),
.BR libsimple_encalloc (3),
.BR libsimple_vcallocn (3),
.BR libsimple_enrealloc (3),
.BR libsimple_vreallocn (3),
.BR libsimple_memalign (3),
.BR libsimple_memalignz (3),
.BR libsimple_vmemalignn (3),
.BR libsimple_enposix_memalign (3),
.BR libsimple_posix_memalignz (3),
.BR libsimple_vposix_memalignn (3),
.BR libsimple_vposix_memalignzn (3),
.BR libsimple_enaligned_alloc (3),
.BR libsimple_aligned_allocz (3),
.BR libsimple_valigned_allocn (3),
.BR libsimple_valigned_alloczn (3),
.BR libsimple_pvalloc (3),
.BR libsimple_pvallocz (3),
.BR libsimple_vpvallocn (3),
.BR libsimple_vpvalloczn (3),
.BR libsimple_valloc (3),
.BR libsimple_vallocz (3),
.BR libsimple_vvallocn (3),
.BR libsimple_vvalloczn (3),
.BR libsimple_vmemalloc (3),
.BR libsimple_varrayalloc (3)
