.TH LIBSIMPLE_STRCHRNUL 3 libsimple
.SH NAME
libsimple_strchrnul \- find a character in a string

.SH SYNOPSIS
.nf
#include <libsimple.h>

char *libsimple_strchrnul(const char *\fIs\fP, int \fIc\fP);

#ifndef strchrnul
# define strchrnul libsimple_strchrnul
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strchrnul ()
function scans the string
.I s
for the first occurence of the character
.I c
(it is converted to a
.BR char ).
If no such character exist in the string,
the string's end is returned.
.PP
The comparison is case-sensitive.

.SH RETURN VALUE
The
.BR libsimple_strchrnul ()
function returns the pointer
.I s
with a minimal offset such that
.IR *r==c||!*r ,
where
.I r
is the returned pointer.

.SH ERRORS
The
.BR libsimple_strchrnul ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strchrnul ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strchrnul ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strchrnul ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_charstrnul_inv (3),
.BR libsimple_strcasechrnul (3),
.BR libsimple_strend (3),
.BR libsimple_strnchrnul (3),
.BR libsimple_memscan (3),
.BR libsimple_inchrset (3),
.BR strchr (3)
