.TH LIBSIMPLE_STRNEQLEN 3 libsimple
.SH NAME
libsimple_strneqlen \- check initial commonality

.SH SYNOPSIS
.nf
#include <libsimple.h>

size_t libsimple_strneqlen(const char *\fIa\fP, const char *\fIb\fP, size_t \fIn\fP);

#ifndef strneqlen
# define strneqlen libsimple_strneqlen
#endif
.fi
.PP
Link with
.IR \-lsimple .

.SH DESCRIPTION
The
.BR libsimple_strneqlen ()
function scans the number of bytes the string
.IR a ,
truncated to
.I n
bytes unless it is shorter,
have in common the string
.IR b ,
truncated to
.I n
bytes unless it is shorter,
at their beginnings.
.PP
The comparison is case-sensitive.

.SH RETURN VALUE
The
.BR libsimple_strneqlen ()
function returns the number of bytes
.I a
and
.I b
(both truncated to
.I n
bytes) have in common at their beginnings.

.SH ERRORS
The
.BR libsimple_strneqlen ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strneqlen ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strneqlen ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strneqlen ()
T}	Async-cancel safety	AC-Safe
.TE

.SH EXAMPLES
None.

.SH APPLICATION USAGE
None.

.SH RATIONALE
None.

.SH FUTURE DIRECTIONS
None.

.SH NOTES
None.

.SH HISTORY
libsimple 1.1

.SH BUGS
None.

.SH SEE ALSO
.BR libsimple_streq (3),
.BR libsimple_strreqlen (3),
.BR libsimple_strcaseeqlen (3),
.BR libsimple_streqlen (3),
.BR libsimple_memeqlen (3)
