.TH LIBSIMPLE_MEMRCASEEQLEN 3 2018-10-23 libsimple
.SH NAME
libsimple_memrcaseeqlen \- check terminal commonality
.SH SYNOPSIS
.nf
#include <libsimple.h>

size_t libsimple_memrcaseeqlen(const void *\fIa\fP, size_t \fIn\fP, const void *\fIb\fP, size_t \fIm\fP);

#ifndef memrcaseeqlen
# define memrcaseeqlen libsimple_memrcaseeqlen
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_memrcaseeqlen ()
function scans the number of bytes the byte array
.IR a ,
with size
.IR n ,
have in common the byte array
.IR b ,
with size
.IR m ,
at their ends.
.PP
The comparison is case-insensitive.
.SH RETURN VALUE
The
.BR libsimple_memrcaseeqlen ()
function returns the number of bytes
.I a
and
.I b
have in common at their ends.
.SH ERRORS
The
.BR libsimple_memrcaseeqlen ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_memrcaseeqlen ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_memrcaseeqlen ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_memrcaseeqlen ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_memreqlen (3),
.BR libsimple_memcaseeqlen (3),
.BR libsimple_strrncaseeqlen (3),
.BR libsimple_strrcaseeqlen (3)
