.TH LIBSIMPLE_STRNMOVE 3 2018-11-16 libsimple
.SH NAME
libsimple_strnmove \- move a string within an array of bytes
.SH SYNOPSIS
.nf
#include <libsimple.h>

static inline void *libsimple_strnmove(void *\fIdest\fP, const void *\fIsrc\fP, size_t \fIn\fP);

#ifndef strnmove
# define strnmove libsimple_strnmove
#endif
.fi
.PP
Link with
.IR \-lsimple .
.SH DESCRIPTION
The
.BR libsimple_strnmove ()
function copies the first
.I n
bytes of the string, including the
NUL byte that terminates it (if any),
.I src
into
.IR dest .
The arrays may overlap.
.SH RETURN VALUE
The
.BR libsimple_strnmove ()
function returns the pointer
.IR dest .
.SH ERRORS
The
.BR libsimple_strnmove ()
function cannot fail.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR libsimple_strnmove ()
T}	Thread safety	MT-Safe
T{
.BR libsimple_strnmove ()
T}	Async-signal safety	AS-Safe
T{
.BR libsimple_strnmove ()
T}	Async-cancel safety	AC-Safe
.TE
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsimple_stpnmove (3),
.BR libsimple_strmove (3),
.BR strncpy (3),
.BR memmove (3)
